FROM node:25-alpine AS development

WORKDIR /app

# Copy package files
COPY ./nextjs/package.json ./nextjs/yarn.lock ./

# Install all dependencies (including dev)
RUN yarn install --frozen-lockfile

# Copy app source
COPY ./nextjs .

# Expose port
EXPOSE 3000

# Start development server with hot reload
CMD ["yarn", "dev"]
